---
title: "datos salud"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(dplyr)
library(readr)
```

# Leer datos

Conjunto de datos salud, en variable 'edad 20-34' contiene unos 

```{r}
salud <- read_excel("datos/salud.xlsx", col_types = c("text",
                                                      "numeric", 
                                                      "numeric", 
                                                      "numeric")
)
```

## Leer archivo.csv

```{r}
salud <- read_csv(file = "datos/salud.csv",
                  col_types = cols(
                    `Codigo iso3` = col_character(),
                    anio = col_number(),
                    `edad 15-17` = col_number(),
                    `edad 20-34` = col_double()
                    ))
```

## Leer archivo excluyendo filas 

```{r}
comentario <- read_csv(file = "datos/comentario.csv", 
                       skip = 1)
```

## Leer archivo sin nombres de columnas

```{r}
encabezado <- read_csv(file = "datos/encabezado.csv",
                    col_names = c("letras","numeros" ))
```


## Leer archivo con NA´s

```{r}
archivo_na <- read_csv(file = "datos/valores_faltantes.csv",
                       skip = 2,
                       na = c(".","NA"))
g```


